


const cidades = ["ABREU E LIMA" ," ARAÇOIABA","CABO DE SANTO AGOSTINHO" , "CAMARAGIBE", "IGARASSU", "ILHA DE ITAMARACÁ", "IPOJUCA", "ITAPISSUMA", "JABOATÃO DOS GUARARAPES", "MORENO","OLINDA" , "PAULISTA","RECIFE" ,"SÃO LORENÇO DA MATA"]



module.exports = cidades